name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test-${{ matrix.os }}-${{ matrix.deno }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Test on the latest stable, and nightly
        deno:
          - e73e8410f66aae052c7c2101d7fd3ce8c8b764e7
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }}

      - run: deno --version

      - name: Format
        if: runner.os == 'Linux'
        run: deno fmt --check

      - name: Lint
        if: runner.os == 'Linux'
        run: deno lint

      - name: Run tests
        run: deno task test
